### ISSUE TITLE
Installation script error

### ISSUE THREAD

**Issue by newuser202201** [pleiszenburg/wenv-kernel#3]
I can install using pip, but when running the installation script I get this error.
By the way, assuming it is installed correctly, how is the wine jupyter server  started ?

python -m wenvkernel.install
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/lib/python3.8/site-packages/wenvkernel/install.py", line 38, in <module>
    _setup_kernels()
  File "/root/anaconda3/lib/python3.8/site-packages/wenvkernel/_core.py", line 61, in setup_kernels
    setup_kernel(bits)
  File "/root/anaconda3/lib/python3.8/site-packages/wenvkernel/_core.py", line 73, in setup_kernel
    _wenv_pip(bits, "install", "ipykernel")
  File "/root/anaconda3/lib/python3.8/site-packages/wenvkernel/_core.py", line 125, in _wenv_pip
    raise SystemError("wenv pip failed", out, err)
SystemError: ('wenv pip failed', '', 'Unknown command or script: "pip"\n')

**Comment by s-m-e** [comment]
`wenv-kernel` is built on top of [wenv](https://github.com/pleiszenburg/wenv) which must be initialized beforehand, see its documentation. This was not required earlier, the instructions in this repo need updating.

Once the kernel is installed, you can start Jupyter Lab just like you usually are. You should see [two new kernels appearing in the launcher](https://github.com/pleiszenburg/wenv-kernel/blob/master/docs/launcher.png).

**Comment by newuser202201** [comment]
Hi, thanks. I run the initialization script "wenv init" , but when running "python -m wenvkernel.install" I still the errors reported above.

**Comment by newuser202201** [comment]
I have installed jupyter in wine and I can run it directly from wine. I can open win32 kernel from wenv, but not win64 kernel.
I have installed a package in wine python 64, so I cannot see it in win 32 kernel. Correct? The init problems above mentioned persist

**Comment by s-m-e** [comment]
> The init problems above mentioned persist

On my todo list - need to reproduce this.

> I have installed jupyter in wine and I can run it directly from wine.

That's also a solution, yes.

> I can open win32 kernel from wenv, but not win64 kernel.

Not in the above mentioned way, correct.

> I have installed a package in wine python 64, so I cannot see it in win 32 kernel. Correct?

Yes.

**Comment by newuser202201** [comment]
I think using the win64 kernel  with wenv would take less memory than using jupyter directly from wine, so hopefully the init will be resolved,  thanks

**Comment by newuser202201** [comment]
Hi, did you check if win64 works now?

**Comment by newuser202201** [comment]
Giving up ..
